import type {HistoryEvent} from './heritage';
export const additionalPlaces=[
 {id:'sanchi',name:'Great Stupa at Sanchi',region:'SANCHI, MADHYA PRADESH',era:'3rd century BCE onwards',dynasty:'Mauryan and later patronage',image:'https://upload.wikimedia.org/wikipedia/commons/5/55/Great_stupa_of_Sanchi.jpg',alt:'Great Stupa at Sanchi with its carved stone gateway',credit:'Nagarjun · CC BY 2.0',imageSource:'https://commons.wikimedia.org/wiki/File:Great_stupa_of_Sanchi.jpg',source:'https://whc.unesco.org/en/list/524/',summary:'Carved gateways and a great dome tracing centuries of Buddhist art.',history:'Sanchi developed under Ashoka in the third century BCE. Later patrons enlarged the stupa, added stone railings and decorated gateways, and built shrines and monasteries. Its architecture records successive phases of Buddhist artistic practice.',damage:'The surviving stupas were restored in the early twentieth century. Sanchi is a conserved archaeological ensemble, not a single monument destroyed in one documented event.'},
 {id:'mahabalipuram',name:'Shore Temple',region:'MAHABALIPURAM, TAMIL NADU',era:'7th–8th century context',dynasty:'Pallava dynasty',image:'https://upload.wikimedia.org/wikipedia/commons/f/f9/Shore_Temple_Mamallapuram.jpg',alt:'The granite Shore Temple at Mahabalipuram near the Bay of Bengal',credit:'Kavita modi · Public domain',imageSource:'https://commons.wikimedia.org/wiki/File:Shore_Temple_Mamallapuram.jpg',source:'https://whc.unesco.org/en/list/249/',summary:'Pallava stone architecture at the edge of the Bay of Bengal.',history:'Mahabalipuram was a Pallava port. Its monuments combine rock-cut caves, monolithic shrines, reliefs and structural temples. The Shore Temple represents the development of structural temple architecture under royal Pallava patronage.',damage:'The surviving temple forms part of a protected coastal ensemble. Excavations around it have revealed buried structures. This collection does not claim that all nearby losses share a single cause.'},
 {id:'khajuraho',name:'Kandariya Mahadeva Temple',region:'KHAJURAHO, MADHYA PRADESH',era:'10th–11th century context',dynasty:'Chandella dynasty',image:'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f1/0121821_Kandariya_Mahadeva_temple%2C_Khajurajo_001.jpg/1280px-0121821_Kandariya_Mahadeva_temple%2C_Khajurajo_001.jpg',alt:'Kandariya Mahadeva Temple at Khajuraho, with its clustered stone spires',credit:'Ms Sarah Welch · CC0 1.0',imageSource:'https://commons.wikimedia.org/wiki/File:0121821_Kandariya_Mahadeva_temple,_Khajurajo_001.jpg',source:'https://whc.unesco.org/en/list/240/',summary:'A rising constellation of spires and a remarkable sculptural tradition.',history:'The Khajuraho temples flourished under the Chandella dynasty in the tenth and eleventh centuries. Kandariya Mahadeva is known for its sculptural surfaces and a high central spire surrounded by smaller spires, characteristic of the Nagara tradition.',damage:'Khajuraho preserves Hindu and Jain temples across several clusters. The survival of the group does not establish a uniform history of damage for each building. Kandariya is presented here as surviving heritage, not as a hypothetical ruin.'},
 {id:'modhera',name:'Sun Temple at Modhera',region:'MODHERA, GUJARAT',era:'11th century',dynasty:'Chaulukya (Solanki) dynasty',image:'https://upload.wikimedia.org/wikipedia/commons/c/cf/Modhera_sun_temple_Gujarat.jpg',alt:'The carved stone halls and stepped tank of the Sun Temple at Modhera',credit:'Chirag5598 - CC BY-SA 4.0',imageSource:'https://commons.wikimedia.org/wiki/File:Modhera_sun_temple_Gujarat.jpg',source:'https://www.gujarattourism.com/content/dam/gujrattourism/images/ebroucher/MODHERASUNTEMPLE.pdf',summary:'A solar sanctuary, ceremonial tank and carved halls aligned with light.',history:'The Sun Temple at Modhera was built in the early eleventh century during the reign of Bhima I of the Chaulukya, or Solanki, dynasty. Its principal elements are the stepped Surya Kund, the Sabha Mandapa and the Gudha Mandapa, arranged as a ritual and architectural sequence dedicated to Surya.',damage:'The sanctuary is no longer an active temple and the image of Surya in the sanctum is absent. The protected complex survives as an Archaeological Survey of India monument; the surviving architecture should not be treated as a complete reconstruction of the original upper tower.'},
 {id:'nalanda',name:'Nalanda Mahavihara',region:'NALANDA, BIHAR',era:'5th–12th century CE',dynasty:'Gupta, Harsha and Pala patronage',image:'https://upload.wikimedia.org/wikipedia/commons/c/c9/Nalanda_University_ruins.JPG',alt:'Brick archaeological remains of ancient Nalanda Mahavihara',credit:'Mrityunjay.nalanda - CC BY-SA 3.0',imageSource:'https://commons.wikimedia.org/wiki/File:Nalanda_University_ruins.JPG',source:'https://whc.unesco.org/en/list/1502/',summary:'A vast Buddhist monastic university whose intellectual network reached across Asia.',history:'Nalanda Mahavihara in Bihar was a major Buddhist monastic and educational centre. Its archaeological remains span the third century BCE to the thirteenth century CE, with a long period of organized scholarship from the fifth century. Monasteries, temples, stupas and artworks reflect the exchange of knowledge across Asia. This entry describes the ancient archaeological site, not the modern university campus at Rajgir.',damage:'The surviving brick ruins preserve successive phases of construction and change. The exact sequence and scale of individual destruction events require separate historical evidence; casualty totals and stories about the duration of a library fire are not presented as verified facts. UNESCO inscribed the archaeological site in 2016.'},
 {id:'shanti-stupa',name:'Shanti Stupa',region:'LEH, LADAKH',era:'1991 CE',dynasty:'Peace Pagoda movement',image:'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/47/Shanti_Stupa_in_Leh.jpg/1280px-Shanti_Stupa_in_Leh.jpg',alt:'White-domed Shanti Stupa overlooking Leh and the Ladakh mountains',credit:'Goutam1962 - CC BY-SA 4.0',imageSource:'https://commons.wikimedia.org/wiki/File:Shanti_Stupa_in_Leh.jpg',source:'https://leh.nic.in/tourist-place/shanti-stupa/',summary:'A modern Buddhist peace pagoda above Leh, framed by high Himalayan light.',history:'Shanti Stupa was built in 1991 by Japanese Buddhist Bhikshu Gyomyo Nakamura as part of the Peace Pagoda mission and to mark 2,500 years of Buddhism. The 14th Dalai Lama consecrated relics at its base. Its two levels carry Buddhist reliefs and a central image, while the hilltop setting opens onto Leh and the surrounding villages.',damage:'This is a modern religious and civic landmark, not a medieval ruin. Its significance lies in the international Buddhist peace movement, its ritual use and its relationship to Leh’s Himalayan landscape.'}
];
const stage=(id:string,year_range:string,actor:string,description:string,index:number):HistoryEvent=>({event_id:`${id}-${index}`,monument_id:id,year_range,actor,description,evidence_type:year_range==='Interpretive status'?'inferred':'documented',source_url:additionalPlaces.find(p=>p.id===id)!.source});
export const additionalEvents:Record<string,HistoryEvent[]>={
 sanchi:[stage('sanchi','3rd c. BCE','Ashokan patronage','An early Buddhist sacred centre is established under Ashoka.',0),stage('sanchi','Later centuries','Successive dynasties','The stupa is enlarged and additional gateways, shrines and monastic buildings are added.',1),stage('sanchi','1989','UNESCO inscription','The Buddhist Monuments at Sanchi join the World Heritage List.',2),stage('sanchi','Present','Conservation','The protected ensemble preserves restored stupas and archaeological remains.',3)],
 mahabalipuram:[stage('mahabalipuram','7th–8th c.','Pallava patronage','Mahabalipuram develops a range of rock-cut and structural monuments.',0),stage('mahabalipuram','Pallava period','Structural architecture','The Shore Temple forms part of the development of structural temple architecture.',1),stage('mahabalipuram','1984','UNESCO inscription','The Group of Monuments at Mahabalipuram joins the World Heritage List.',2),stage('mahabalipuram','Present','ASI conservation','The coastal monuments and excavated remains are protected and monitored.',3)],
 khajuraho:[stage('khajuraho','10th–11th c.','Chandella patronage','The temple groups develop during the Chandella period.',0),stage('khajuraho','Medieval period','Temple art','Kandariya embodies a mature Nagara composition with a principal spire and subsidiary spires.',1),stage('khajuraho','1986','UNESCO inscription','The Khajuraho Group of Monuments joins the World Heritage List.',2),stage('khajuraho','Present','ASI conservation','Surviving temple clusters are conserved within a protected landscape.',3)],
 modhera:[stage('modhera','1026–1027','Bhima I and Chaulukya patronage','The Sun Temple complex is built during the reign of Bhima I of the Chaulukya dynasty.',0),stage('modhera','Medieval period','Ritual architecture','The Surya Kund, Sabha Mandapa and Gudha Mandapa form a ceremonial sequence dedicated to the sun.',1),stage('modhera','Present','ASI protection','The surviving complex is protected as an archaeological monument and is no longer a functioning temple.',2),stage('modhera','Interpretive status','Architectural reconstruction','The present 3D view is schematic; the lost upper sanctuary is not reconstructed as established fact.',3)],
 nalanda:[stage('nalanda','5th century CE','Gupta patronage','Nalanda Mahavihara develops as a residential Buddhist centre of learning in Magadha.',0),stage('nalanda','5th–12th c. CE','International scholarship','Monastic colleges and temples serve students and teachers connected to many parts of Asia.',1),stage('nalanda','13th century CE','End of the represented period','UNESCO dates the archaeological remains through the thirteenth century; this alone does not establish a precise destruction date or cause.',2),stage('nalanda','2016','UNESCO inscription','The Archaeological Site of Nalanda Mahavihara at Nalanda, Bihar is inscribed on the World Heritage List.',3)],
 'shanti-stupa':[stage('shanti-stupa','1991','Gyomyo Nakamura and Peace Pagoda movement','The modern Shanti Stupa is completed on a hill above Leh.',0),stage('shanti-stupa','1991','14th Dalai Lama','Buddhist relics are enshrined at the base during consecration.',1),stage('shanti-stupa','Present','Religious and civic landmark','The stupa remains a site of devotion and a viewpoint over Leh and the surrounding villages.',2),stage('shanti-stupa','Interpretive status','Modern heritage','The 3D view is an educational schematic of a living modern monument, not a reconstruction of an ancient ruin.',3)]
};
export const additionalSources=[
 {monument:'modhera',title:'Gujarat Tourism - Sun Temple, Modhera',url:'https://www.gujarattourism.com/content/dam/gujrattourism/images/ebroucher/MODHERASUNTEMPLE.pdf',note:'Monument protection and architectural context.'},
 {monument:'nalanda',title:'UNESCO - Nalanda Mahavihara inscription decision',url:'https://whc.unesco.org/en/list/1502/',note:'World Heritage inscription, significance and criteria.'},
 {monument:'nalanda',title:'Nalanda University - History and Revival',url:'https://nalandauniv.edu.in/about-nalanda/history-and-revival/',note:'Modern university history and the revival connection.'},
 {monument:'shanti-stupa',title:'District Administration Leh - Shanti Stupa',url:'https://leh.nic.in/tourist-place/shanti-stupa/',note:'1991 date, patronage, relics and current site description.'}
];
export const placeContext:Record<string,{lat:number;lng:number;country:string;videoId?:string;videoSource:string;videoCredit?:string;unesco:boolean}>={
 hampi:{lat:15.3421,lng:76.4753,country:'India',videoSource:'https://www.unesco.org/archives/multimedia/document-1005',unesco:true},
 konark:{lat:19.8876,lng:86.0945,country:'India',videoId:'GqYAggbOh9I',videoSource:'https://whc.unesco.org/en/list/246/video',unesco:true},
 sanchi:{lat:23.47944,lng:77.73972,country:'India',videoId:'lNgSJgUqGIM',videoSource:'https://whc.unesco.org/en/list/524/video',unesco:true},
 mahabalipuram:{lat:12.6165,lng:80.1993,country:'India',videoId:'CC3S2jTwqN4',videoSource:'https://whc.unesco.org/en/list/249/video',unesco:true},
 khajuraho:{lat:24.853,lng:79.9197,country:'India',videoId:'1XLA1XdMCCQ',videoSource:'https://whc.unesco.org/en/list/240/video',unesco:true},
 modhera:{lat:23.5836,lng:72.1333,country:'India',videoId:'00M83mZ--7E',videoSource:'https://www.youtube.com/watch?v=00M83mZ--7E',videoCredit:'Gujarat Tourism - Modhera Sun Temple',unesco:false},
 nalanda:{lat:25.1367,lng:85.4437,country:'India',videoId:'c-cAnvDbHq4',videoSource:'https://nalandauniv.edu.in/videos/',videoCredit:'Nalanda University video gallery - visit to the ancient ruins (not the modern campus)',unesco:true},
 'shanti-stupa':{lat:34.17375,lng:77.57502,country:'India',videoId:'tJz2gZLHjgU',videoSource:'https://www.youtube.com/watch?v=tJz2gZLHjgU',videoCredit:'The World of Madhu Sharma - independent travel footage, not an academic history source',unesco:false}
};
