import type {HistoryEvent} from './heritage';
export const additionalPlaces=[
 {id:'sanchi',name:'Great Stupa at Sanchi',region:'SANCHI, MADHYA PRADESH',era:'3rd century BCE onwards',dynasty:'Mauryan and later patronage',image:'https://upload.wikimedia.org/wikipedia/commons/5/55/Great_stupa_of_Sanchi.jpg',alt:'Great Stupa at Sanchi with its carved stone gateway',credit:'Nagarjun · CC BY 2.0',imageSource:'https://commons.wikimedia.org/wiki/File:Great_stupa_of_Sanchi.jpg',source:'https://whc.unesco.org/en/list/524/',summary:'Carved gateways and a great dome tracing centuries of Buddhist art.',history:'Sanchi developed under Ashoka in the third century BCE. Later patrons enlarged the stupa, added stone railings and decorated gateways, and built shrines and monasteries. Its architecture records successive phases of Buddhist artistic practice.',damage:'The surviving stupas were restored in the early twentieth century. Sanchi is a conserved archaeological ensemble, not a single monument destroyed in one documented event.'},
 {id:'mahabalipuram',name:'Shore Temple',region:'MAHABALIPURAM, TAMIL NADU',era:'7th–8th century context',dynasty:'Pallava dynasty',image:'https://upload.wikimedia.org/wikipedia/commons/f/f9/Shore_Temple_Mamallapuram.jpg',alt:'The granite Shore Temple at Mahabalipuram near the Bay of Bengal',credit:'Kavita modi · Public domain',imageSource:'https://commons.wikimedia.org/wiki/File:Shore_Temple_Mamallapuram.jpg',source:'https://whc.unesco.org/en/list/249/',summary:'Pallava stone architecture at the edge of the Bay of Bengal.',history:'Mahabalipuram was a Pallava port. Its monuments combine rock-cut caves, monolithic shrines, reliefs and structural temples. The Shore Temple represents the development of structural temple architecture under royal Pallava patronage.',damage:'The surviving temple forms part of a protected coastal ensemble. Excavations around it have revealed buried structures. This collection does not claim that all nearby losses share a single cause.'},
 {id:'khajuraho',name:'Kandariya Mahadeva Temple',region:'KHAJURAHO, MADHYA PRADESH',era:'10th–11th century context',dynasty:'Chandella dynasty',image:'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f1/0121821_Kandariya_Mahadeva_temple%2C_Khajurajo_001.jpg/1280px-0121821_Kandariya_Mahadeva_temple%2C_Khajurajo_001.jpg',alt:'Kandariya Mahadeva Temple at Khajuraho, with its clustered stone spires',credit:'Ms Sarah Welch · CC0 1.0',imageSource:'https://commons.wikimedia.org/wiki/File:0121821_Kandariya_Mahadeva_temple,_Khajurajo_001.jpg',source:'https://whc.unesco.org/en/list/240/',summary:'A rising constellation of spires and a remarkable sculptural tradition.',history:'The Khajuraho temples flourished under the Chandella dynasty in the tenth and eleventh centuries. Kandariya Mahadeva is known for its sculptural surfaces and a high central spire surrounded by smaller spires, characteristic of the Nagara tradition.',damage:'Khajuraho preserves Hindu and Jain temples across several clusters. The survival of the group does not establish a uniform history of damage for each building. Kandariya is presented here as surviving heritage, not as a hypothetical ruin.'}
];
const stage=(id:string,year_range:string,actor:string,description:string,index:number):HistoryEvent=>({event_id:`${id}-${index}`,monument_id:id,year_range,actor,description,evidence_type:'documented',source_url:additionalPlaces.find(p=>p.id===id)!.source});
export const additionalEvents:Record<string,HistoryEvent[]>={
 sanchi:[stage('sanchi','3rd c. BCE','Ashokan patronage','An early Buddhist sacred centre is established under Ashoka.',0),stage('sanchi','Later centuries','Successive dynasties','The stupa is enlarged and additional gateways, shrines and monastic buildings are added.',1),stage('sanchi','1989','UNESCO inscription','The Buddhist Monuments at Sanchi join the World Heritage List.',2),stage('sanchi','Present','Conservation','The protected ensemble preserves restored stupas and archaeological remains.',3)],
 mahabalipuram:[stage('mahabalipuram','7th–8th c.','Pallava patronage','Mahabalipuram develops a range of rock-cut and structural monuments.',0),stage('mahabalipuram','Pallava period','Structural architecture','The Shore Temple forms part of the development of structural temple architecture.',1),stage('mahabalipuram','1984','UNESCO inscription','The Group of Monuments at Mahabalipuram joins the World Heritage List.',2),stage('mahabalipuram','Present','ASI conservation','The coastal monuments and excavated remains are protected and monitored.',3)],
 khajuraho:[stage('khajuraho','10th–11th c.','Chandella patronage','The temple groups develop during the Chandella period.',0),stage('khajuraho','Medieval period','Temple art','Kandariya embodies a mature Nagara composition with a principal spire and subsidiary spires.',1),stage('khajuraho','1986','UNESCO inscription','The Khajuraho Group of Monuments joins the World Heritage List.',2),stage('khajuraho','Present','ASI conservation','Surviving temple clusters are conserved within a protected landscape.',3)]
};
export const placeContext:Record<string,{lat:number;lng:number;country:string;videoId?:string;videoSource:string;unesco:boolean}>={
 hampi:{lat:15.3421,lng:76.4753,country:'India',videoSource:'https://www.unesco.org/archives/multimedia/document-1005',unesco:true},
 konark:{lat:19.8876,lng:86.0945,country:'India',videoId:'GqYAggbOh9I',videoSource:'https://whc.unesco.org/en/list/246/video',unesco:true},
 sanchi:{lat:23.47944,lng:77.73972,country:'India',videoId:'lNgSJgUqGIM',videoSource:'https://whc.unesco.org/en/list/524/video',unesco:true},
 mahabalipuram:{lat:12.6165,lng:80.1993,country:'India',videoId:'CC3S2jTwqN4',videoSource:'https://whc.unesco.org/en/list/249/video',unesco:true},
 khajuraho:{lat:24.853,lng:79.9197,country:'India',videoId:'1XLA1XdMCCQ',videoSource:'https://whc.unesco.org/en/list/240/video',unesco:true}
};
