"use client";
import {useEffect,useState,type ReactNode} from 'react';
import {useRouter} from 'next/navigation';
import type {User} from '@supabase/supabase-js';
import {Landmark,ArrowRight,Mail,LockKeyhole,Eye,EyeOff} from 'lucide-react';
import {getSupabase} from '../lib/supabase';
import {monuments} from './heritage';
export function SessionGate({children}:{children:(user:User,logout:()=>Promise<void>)=>ReactNode}){const router=useRouter();const [user,setUser]=useState<User|null>(null);useEffect(()=>{let active=true;let cleanup:(()=>void)|undefined;getSupabase().then(async client=>{const {data}=client.auth.onAuthStateChange((event,session)=>{if(!active)return;if(event==='SIGNED_OUT'){setUser(null);router.replace('/login')}else if(session?.user&&event!=='INITIAL_SESSION')setUser(session.user)});cleanup=()=>data.subscription.unsubscribe();const {data:verified,error}=await client.auth.getUser();if(!active)return;if(error||!verified.user){setUser(null);router.replace('/login')}else setUser(verified.user)}).catch(()=>{if(active)router.replace('/login')});return()=>{active=false;cleanup?.()}},[router]);const logout=async()=>{const client=await getSupabase();const {error}=await client.auth.signOut();if(error)throw error;setUser(null);router.replace('/login')};return user?children(user,logout):<div className="auth-loading"><Landmark/><p>Opening Kaal-Darshan...</p></div>}
export function LoginPage(){const router=useRouter();const [mode,setMode]=useState<'login'|'signup'|'reset'|'update'>('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[show,setShow]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[configured,setConfigured]=useState(false),[needsConfirmation,setNeedsConfirmation]=useState(false),[resendAt,setResendAt]=useState(0);
 useEffect(()=>{let active=true;let unsubscribe:(()=>void)|undefined;const recovery=new URLSearchParams(window.location.search).get('recovery')==='1';if(recovery)setMode('update');getSupabase().then(async client=>{if(!active)return;setConfigured(true);const {data}=client.auth.onAuthStateChange((event,session)=>{if(!active)return;if(event==='PASSWORD_RECOVERY')setMode('update');else if(session&&event==='SIGNED_IN'&&!recovery)router.replace('/')});unsubscribe=()=>data.subscription.unsubscribe();const {data:user}=await client.auth.getUser();if(active&&user.user&&!recovery)router.replace('/')}).catch(e=>{if(active)setMessage(e.message)});return()=>{active=false;unsubscribe?.()}},[router]);
 async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setMessage('');try{const client=await getSupabase();if(mode==='login'){const {error}=await client.auth.signInWithPassword({email,password});if(error){if(error.code==='email_not_confirmed'){setNeedsConfirmation(true);throw Error('Confirm your email before signing in. Check your inbox and spam folder, or resend the confirmation below.')}throw error}router.replace('/')}else if(mode==='signup'){const {data,error}=await client.auth.signUp({email,password,options:{data:{display_name:name},emailRedirectTo:window.location.origin+'/'}});if(error)throw error;if(data.session)router.replace('/');else {setNeedsConfirmation(true);setMode('login');setMessage('Check your email to confirm your account, then sign in. If you already registered, use your existing password or reset it.')}}else if(mode==='reset'){const {error}=await client.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin+'/login?recovery=1'});if(error)throw error;setMessage('If this address has an account, a password reset email is on its way.')}else{const {error}=await client.auth.updateUser({password});if(error)throw error;router.replace('/')}}catch(error){setMessage(error instanceof Error?error.message:'Sign-in could not be completed.')}finally{setBusy(false)}}
 async function resendConfirmation(){if(!email.trim()){setMessage('Enter your email address first.');return}if(Date.now()<resendAt){setMessage('Please wait one minute before requesting another confirmation email.');return}setBusy(true);setMessage('');try{const client=await getSupabase();const {error}=await client.auth.resend({type:'signup',email:email.trim(),options:{emailRedirectTo:window.location.origin+'/'}});if(error)throw error;setResendAt(Date.now()+60000);setMessage('Confirmation requested. Check your inbox and spam folder, then return here to sign in.')}catch(error){setMessage(error instanceof Error?error.message:'Could not resend confirmation.')}finally{setBusy(false)}}
 async function google(){setBusy(true);setMessage('');try{const client=await getSupabase();const {error}=await client.auth.signInWithOAuth({provider:'google',options:{redirectTo:window.location.origin+'/'}});if(error)throw error}catch(error){setMessage(error instanceof Error?error.message:'Google sign-in could not start.');setBusy(false)}}
 return <main className="login-page"><img className="login-background" src={monuments[0].image} alt="Vittala Temple stone chariot, Hampi"/><div className="login-overlay"/><a className="brand login-brand" href="/login"><Landmark size={30}/><span>KAAL-DARSHAN<small>THE PAST, IN PERSPECTIVE</small></span></a><section className="login-story"><span className="eyebrow">YOUR JOURNEY THROUGH TIME</span><h1>Kaal-Darshan</h1><p>Extraordinary places.<br/>Stories worth discovering.</p><span className="login-credit">Vittala Temple, Hampi · Prashmob / CC BY-SA 4.0</span></section><section className="login-form"><span className="eyebrow">WELCOME, EXPLORER</span><h2>{mode==='signup'?'Create your account':mode==='reset'?'Reset your password':mode==='update'?'Choose a new password':'Sign in to explore'}</h2><p>Your places, discoveries and memories, together.</p>{(mode==='login'||mode==='signup')&&<><button className="google-button" disabled={!configured||busy} onClick={google}><span aria-hidden="true">G</span> Continue with Google</button><div className="auth-divider">or use email</div></>}<form onSubmit={submit}>{mode==='signup'&&<label>Your name<input autoComplete="name" value={name} onChange={e=>setName(e.target.value)} required maxLength={100}/></label>}{mode!=='update'&&<label>Email address<div className="auth-input"><Mail size={17}/><input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required/></div></label>}{mode!=='reset'&&<label>Password<div className="auth-input"><LockKeyhole size={17}/><input type={show?'text':'password'} minLength={8} autoComplete={mode==='login'?'current-password':'new-password'} value={password} onChange={e=>setPassword(e.target.value)} required/><button type="button" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label>}{mode==='login'&&<button className="forgot" type="button" onClick={()=>{setMode('reset');setMessage('')}}>Forgot password?</button>}<button className="primary auth-submit" disabled={busy||!configured}>{busy?'Please wait...':mode==='signup'?'Create account':mode==='reset'?'Send reset link':mode==='update'?'Update password':'Sign in'}<ArrowRight size={17}/></button></form><p role="status" className="auth-message">{message}</p>{(mode==='login'||needsConfirmation)&&mode!=='update'&&<button type="button" className="forgot" disabled={!configured||busy} onClick={resendConfirmation}>Resend confirmation email</button>}<button className="auth-switch" onClick={()=>{setMode(mode==='login'?'signup':'login');if(configured)setMessage('')}}>{mode==='login'?'New here? Create an account':'Back to sign in'}</button><p className="auth-privacy">Your saved places and contributions belong to your account.</p></section></main>
}
