import {additionalPlaces,additionalEvents,additionalSources} from './additional-heritage';
export const monuments = [
 {id:"hampi",name:"Vittala Temple",region:"HAMPI, KARNATAKA",era:"15th–16th century",dynasty:"Vijayanagara Empire",image:"https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ae/Stone_Chariot_View%2C_Hampi.jpg/1280px-Stone_Chariot_View%2C_Hampi.jpg",alt:"The stone chariot and surviving structures in the Vittala Temple courtyard, Hampi",credit:"Prashmob · CC BY-SA 4.0",imageSource:"https://commons.wikimedia.org/wiki/File:Stone_Chariot_View,_Hampi.jpg",source:"https://www.asihampicircle.in/vittala-temple-complex-and-its-surrounding/",summary:"Pillared halls, a stone chariot, and the echoes of an extraordinary capital.",history:"Vittala Temple belongs to the Vijayanagara period. Its complex includes a sanctuary, pillared halls and the celebrated stone chariot shrine. The surviving ensemble reveals an ambitious tradition of temple architecture.",damage:"Hampi was pillaged following the Battle of Talikota in 1565. ASI records worship at Vittala until that year. This does not establish a precise date or cause for every missing element in the complex."},
 {id:"konark",name:"Konark Sun Temple",region:"KONARK, ODISHA",era:"13th century",dynasty:"Eastern Ganga dynasty",image:"https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6e/Sun_Temple_at_Konark.jpg/1280px-Sun_Temple_at_Konark.jpg",alt:"The surviving assembly hall of Konark Sun Temple with its sculpted stone platform",credit:"Mayank Choudhary · CC BY-SA 3.0",imageSource:"https://commons.wikimedia.org/wiki/File:Sun_Temple_at_Konark.jpg",source:"https://whc.unesco.org/en/list/246/",summary:"A monumental chariot to the sun, carved in stone and shaped by time.",history:"Built in the 13th century during the reign of Narasimhadeva I, Konark was conceived as the chariot of Surya. Its sculpted wheels and surviving hall are defining examples of Kalinga architecture.",damage:"The principal sanctuary tower no longer stands. Accounts of its loss differ; this pilot does not attribute its collapse to a single invasion or natural event."}
,...additionalPlaces];
export const sources=[{monument:"hampi",title:"Archaeological Survey of India · Vittala Temple",url:monuments[0].source,note:"Architectural components and the period of worship."},{monument:"hampi",title:"UNESCO · Group of Monuments at Hampi",url:"https://whc.unesco.org/en/list/241/",note:"Vijayanagara context, 1565 destruction and World Heritage inscription."},{monument:"konark",title:"UNESCO · Sun Temple, Konark",url:monuments[1].source,note:"13th-century patronage, chariot symbolism and heritage significance."},{monument:"konark",title:"UNESCO · Konark documentation",url:"https://whc.unesco.org/en/list/246/documents/",note:"Nomination records and site plans; not a dimensional source for this mesh."},...additionalSources];
export type HistoryEvent={event_id:string;monument_id:string;year_range:string;actor:string;description:string;evidence_type:"documented"|"inferred"|"disputed";source_url:string};
export const events:Record<string,HistoryEvent[]>={...additionalEvents,hampi:[
 {event_id:"h1",monument_id:"hampi",year_range:"15th–16th c.",actor:"Vijayanagara patronage",description:"The temple develops during the Vijayanagara period. The intact model is an architectural interpretation.",evidence_type:"documented",source_url:monuments[0].source},
 {event_id:"h2",monument_id:"hampi",year_range:"1565",actor:"Battle of Talikota and pillage",description:"The defeat of Vijayanagara is followed by the pillage of Hampi. Individual structural losses are not dated by this general account.",evidence_type:"documented",source_url:sources[1].url},
 {event_id:"h3",monument_id:"hampi",year_range:"1986",actor:"UNESCO inscription",description:"The Group of Monuments at Hampi is inscribed on the World Heritage List.",evidence_type:"documented",source_url:sources[1].url},
 {event_id:"h4",monument_id:"hampi",year_range:"Present",actor:"Protected heritage",description:"Surviving stone structures remain part of a protected archaeological landscape. The model simplifies their current form.",evidence_type:"documented",source_url:sources[1].url}],konark:[
 {event_id:"k1",monument_id:"konark",year_range:"13th century",actor:"Narasimhadeva I",description:"The Sun Temple is built under Eastern Ganga patronage as a representation of Surya's chariot.",evidence_type:"documented",source_url:monuments[1].source},
 {event_id:"k2",monument_id:"konark",year_range:"Loss over time",actor:"Multiple proposed causes",description:"The main sanctuary tower is lost. A single cause or exact sequence is not established in this curated dataset.",evidence_type:"disputed",source_url:monuments[1].source},
 {event_id:"k3",monument_id:"konark",year_range:"1984",actor:"UNESCO inscription",description:"Konark Sun Temple is inscribed on the World Heritage List.",evidence_type:"documented",source_url:monuments[1].source},
 {event_id:"k4",monument_id:"konark",year_range:"Present",actor:"Protected heritage",description:"The surviving hall, platform and sculpture preserve the temple's architectural legacy.",evidence_type:"documented",source_url:monuments[1].source}]};
