"use client";
import {useState} from 'react';
import {placeContext} from './additional-heritage';
import type {Place} from './library';
export default function HeritageVideo({place}:{place:Place}){
 const [playing,setPlaying]=useState(false),[panorama,setPanorama]=useState(false);
 const context=placeContext[place.id],panoramaId=place.id==='hampi'?'xf_MlReoHLM':undefined;
 const id=panorama?panoramaId:context?.videoId;
 return <><div className="segmented video-modes"><button className={!panorama?'selected':''} onClick={()=>{setPanorama(false);setPlaying(false)}}>Heritage film</button><button className={panorama?'selected':''} onClick={()=>{setPanorama(true);setPlaying(false)}}>360 video</button></div><article className="heritage-film"><div className="film-player">{playing&&id?<iframe title={place.name+' - '+(panorama?'360 video':'heritage film')} src={'https://www.youtube-nocookie.com/embed/'+id+'?autoplay=1'} allow="autoplay; encrypted-media; picture-in-picture; gyroscope; accelerometer" allowFullScreen/>:<button className="film-cover" aria-label={panorama?'Watch 360 video':'Watch heritage film'} onClick={()=>setPlaying(true)} disabled={!id}><img src={place.image} alt={place.alt}/>{id&&<span>{panorama?'Watch 360 video':'Watch heritage film'}</span>}</button>}</div><div className="film-caption"><h3>{panorama?'360 footage':place.name+': real heritage footage'}</h3>{panorama?<>{panoramaId?<><p>Google Arts &amp; Culture: Incredible India. Includes Hampi alongside Goa, Delhi and Amritsar; not a dedicated scan of Vittala Temple.</p><a href={'https://www.youtube.com/watch?v='+panoramaId} target="_blank" rel="noreferrer">Open original 360 film</a></>:<><p>A verified 360 video for this place has not been added yet.</p><p>Your own equirectangular video can be played in panorama mode below.</p></>}</>:<><p>{context?.videoCredit||'Original publisher'}. Original publisher retains all rights.</p>{context?.videoSource&&<a href={context.videoSource} target="_blank" rel="noreferrer">Watch at the source</a>}</>}<p className="small">External playback depends on the publisher. YouTube may require opening the original film for spherical controls.</p></div></article></>;
}
