import {monuments,events,HistoryEvent} from './heritage';
import {signedInUser} from '../lib/supabase';
export type Place=typeof monuments[number] & {country?:string;latitude?:string;longitude?:string};
export type MediaItem={id:string;name:string;type:'image'|'video'|'model';blob?:Blob;url?:string;storagePath?:string};
export type Library={places:Place[];timelines:Record<string,HistoryEvent[]>;media:Record<string,MediaItem[]>};
export const initialLibrary:Library={places:monuments,timelines:events,media:{}};
export async function loadLibrary():Promise<Library>{const {supabase,user}=await signedInUser();const {data,error}=await supabase.from('user_libraries').select('content').eq('user_id',user.id).maybeSingle();if(error)throw error;const saved=data?.content as Library|undefined;const value=saved?{...saved,places:[...saved.places,...monuments.filter(p=>!saved.places.some(s=>s.id===p.id))],timelines:{...events,...saved.timelines}}:initialLibrary;return resolveMedia(value)}
async function resolveMedia(value:Library){const {supabase}=await signedInUser();const media:Library['media']={};for(const [id,items]of Object.entries(value.media)){media[id]=await Promise.all(items.map(async item=>{if(!item.storagePath)return item;const {data,error}=await supabase.storage.from('heritage-media').createSignedUrl(item.storagePath,86400);if(error)throw error;return {...item,url:data.signedUrl}}))}return {...value,media}}
export async function storeLibrary(value:Library):Promise<Library>{const {supabase,user}=await signedInUser();const media:Library['media']={};for(const [id,items]of Object.entries(value.media)){media[id]=[];for(const item of items){let storagePath=item.storagePath;if(item.blob){storagePath=`${user.id}/${id}/${item.id}`;const {error}=await supabase.storage.from('heritage-media').upload(storagePath,item.blob,{upsert:true,contentType:item.blob.type||'application/octet-stream'});if(error)throw error}media[id].push({id:item.id,name:item.name,type:item.type,...(storagePath?{storagePath}:{url:item.url})})}}const stored={...value,media};const {error}=await supabase.from('user_libraries').upsert({user_id:user.id,content:stored,updated_at:new Date().toISOString()});if(error)throw error;return resolveMedia(stored)}
export async function loadPreferences(){const {supabase,user}=await signedInUser();const {data,error}=await supabase.from('profiles').select('saved_places,visited_places').eq('id',user.id).maybeSingle();if(error)throw error;return {saved:(data?.saved_places||[]) as string[],visited:(data?.visited_places||[]) as string[]}}
let preferenceQueue:Promise<void>=Promise.resolve();
export async function savePreferences(saved:string[],visited:string[]){const {supabase,user}=await signedInUser();const write=async()=>{const {error}=await supabase.from('profiles').upsert({id:user.id,display_name:user.user_metadata.display_name||user.user_metadata.full_name||'',saved_places:saved,visited_places:visited,updated_at:new Date().toISOString()});if(error)throw error};preferenceQueue=preferenceQueue.catch(()=>{}).then(write);return preferenceQueue}
export function safeURL(value:string){return !value || /^https?:\/\//i.test(value)}
