import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=await PGlite.create();
const a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222';
try{
 await db.exec(`create role anon;create role authenticated;create schema auth;create schema storage;
 create table auth.users(id uuid primary key);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);
 create function storage.foldername(name text) returns text[] language sql immutable as $$select string_to_array(name,'/')$$;
 alter table storage.objects enable row level security;
 grant usage on schema public,auth,storage to anon,authenticated;
 grant select,insert,update,delete on storage.objects to authenticated;
 insert into auth.users values ('${a}'),('${b}');`);
 await db.exec(await readFile('supabase/schema.sql','utf8'));
 const hardening=await readFile('supabase/security-hardening.sql','utf8');
 await db.exec(hardening);await db.exec(hardening);
 await db.query('insert into public.profiles(id) values ($1),($2)',[a,b]);
 await db.query("select set_config('request.jwt.claim.sub',$1,false)",[a]);await db.exec('set role authenticated');
 assert.deepEqual((await db.query('select id from public.profiles')).rows.map(r=>r.id),[a]);
 assert.equal((await db.query('update public.profiles set display_name=$1 where id=$2',['forged',b])).affectedRows,0);
 const place={id:'test',name:'Test',region:'India',era:'1000',dynasty:'Test',image:'/heritage/hampi.jpg',alt:'Test',credit:'Test',imageSource:'https://example.com',source:'https://example.com',summary:'Test',history:'Test',damage:'Test'};
 const content={places:[place],timelines:{test:Array.from({length:4},(_,i)=>({event_id:`e${i}`,monument_id:'test',year_range:'1000',actor:'Test',description:'Test',evidence_type:'inferred',source_url:'https://example.com'}))},media:{}};
 await db.query('insert into public.user_libraries(user_id,content) values ($1,$2)',[a,JSON.stringify(content)]);
 await assert.rejects(()=>db.query('insert into public.user_libraries(user_id,content) values ($1,$2)',[b,JSON.stringify(content)]));
 await assert.rejects(()=>db.query('update public.user_libraries set content=$1 where user_id=$2',[JSON.stringify({...content,places:[{...place,image:'javascript:alert(1)'}]}),a]));
 await assert.rejects(()=>db.query('update public.user_libraries set content=$1 where user_id=$2',[JSON.stringify({...content,media:{test:[{id:'media',name:'Test',type:'image',storagePath:`${b}/test/media`}]}}),a]));
 await db.query('insert into storage.objects(bucket_id,name) values ($1,$2)',['heritage-media',`${a}/test/media`]);
 await assert.rejects(()=>db.query('insert into storage.objects(bucket_id,name) values ($1,$2)',['heritage-media',`${b}/test/media`]));
 await assert.rejects(()=>db.query('insert into storage.objects(bucket_id,name) values ($1,$2)',['heritage-media',`${a}/../media`]));
 await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[b]);await db.exec('set role authenticated');
 assert.equal((await db.query('select * from public.user_libraries')).rows.length,0);
 assert.equal((await db.query('select * from storage.objects')).rows.length,0);
 assert.equal((await db.query('delete from storage.objects')).affectedRows,0);
 await db.exec('reset role;set role anon');
 await assert.rejects(()=>db.query('select * from public.profiles'));
 await assert.rejects(()=>db.query('select * from public.user_libraries'));
 console.log('Database tests passed: migration twice, two-user RLS, forged ownership, malicious URLs, private storage and anonymous denial. No hosted data modified.');
}finally{await db.close()}
